### ISSUE TITLE
Hugoのブログサンプルサイトを作る

### ISSUE THREAD

**Issue by DQNEO** [DQNEO/memo#8]

**Comment by DQNEO** [comment]
ローカルで作ってみた。
そこそこちゃんと動いた。

**Comment by DQNEO** [comment]
tomlはこんなん。

``` toml
baseurl = "http://test.sakusakutto.jp/"
languageCode = "ja-jp"
title = "DQNEO起業日記"
uglyurls = true
copyright = "&copy; 2015 @DQNEO All Rights Reserved."

[taxonomies]
tag = "tags"
category = "categories"
series = "series"

[params]
twitter = "DQNEO"
github = "DQNEO"
author = "DQNEO"
avatar = "/images/avatar.jpg"
subtitle = "First they ignore you"
```
